# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e6528eb7c379d9af089f02ea711c8de"
name = "example-app-qr-code-remix"
application_url = "https://500d-2a00-23c5-fd83-d501-61c0-8558-34b5-66b2.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0de1dc98.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://500d-2a00-23c5-fd83-d501-61c0-8558-34b5-66b2.ngrok-free.app/auth/callback",
  "https://500d-2a00-23c5-fd83-d501-61c0-8558-34b5-66b2.ngrok-free.app/auth/shopify/callback",
  "https://500d-2a00-23c5-fd83-d501-61c0-8558-34b5-66b2.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
